### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yu-2t** [yu-2t/furima-29597#8]
# URL
https://furima-29597.herokuapp.com/

# basic認証
ID: yu-2t
pass: 0204

# 出品者
mail: yyy@yyy
pass: 123qwe

 # 購入者
mail: ttt@ttt
pass: 123qwe

# クレジットカード
番号: 4242424242424242
期限: 3/33
セキュリティーコード: 123

**Comment by iwataayumu** [comment]
@yu-2t さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
